import 'bootstrap/dist/css/bootstrap.min.css'
import '@/styles/globals.css'
import styles from '@/styles/App.module.css'

import Head from 'next/head'
import { Inter } from 'next/font/google'
import type { AppProps } from 'next/app'
import { Container } from 'react-bootstrap'
import NavBar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <div className={inter.className}>
        <Head>
          <title>My Blog</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar></NavBar>
        <Container className={styles.pageContainer}>
          <Component {...pageProps} />
        </Container>
      </div>
    </>
  )
}
